import Head from 'next/head'

export default function Home() {
  
  return (
    <div className='bg-black text-white'>
      <Head>
        <title>Block State</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='px-40 mt-2 text-white flex flex-col'>
        <span>Buy, Sell and Rent Real Estate Properties.</span>
      </div>

      <div className='flex items-center justify-center mt-auto'>
        <span>Built by  <a href="https://twitter.com/dineshaitham1" target="_blank" className='underline underline-offset-2'>Dinesh Aitham</a></span>
      </div>

    </div>
  )
}
