import Head from 'next/head'
import {AiOutlineCopyrightCircle} from 'react-icons/ai'
export default function Home() {
  
  return (
    <div className='bg-black text-white'>
      <Head>
        <title>Block State</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='px-40 mt-2 text-white flex pt-20 items-center justify-between tracking-wider'>
        {/* <span>Buy, Sell and Rent Real Estate Properties.</span> */}
        <div className='w-1/2 flex flex-col'>
          <div className='text-xl font-bold'>Sell or Rent your property on Block State</div>
          <span>Become a part of the growing Blockchain based Block State family.To list your property you need to pay 1 matic as listings price and listings was completely free for pro member.</span>
          <a href='./sell'><button className='bg-blue-500 text-white px-4 py-2 rounded-xl mt-4'>List your property</button></a>
        </div>
        <div>
          <img src="./sale.jpg" className='w-128 rounded-lg'></img>
        </div>
      </div>

      <div>
        <div className='px-40 mt-2 text-white flex pt-20 justify-center tracking-wider'>
          <div className='flex flex-col items-center justify-center'> 
                <span className='text-sm text-gray-400'>ALL PROPERTY NEEDS - ONE PORTAL</span>
                <span className='text-3xl font-semibold '>Find Better Places to Live, Work </span>
                <span className='text-3xl font-semibold '>and Wonder...</span>
            </div>
          </div>
        <div className='px-40 mt-2 text-white flex py-10 justify-center items-center gap-20'>
            <img src="./home.png" className='w-128 rounded-lg'></img>
            <div className='flex flex-col gap-1'>
              <span className='uppercase text-gray-400'>buy a home</span>
              <span className='text-xl font-semibold'>Find, Buy & Own Your</span>
              <span className='text-xl font-semibold'>Dream Home</span>
              <span className='text-gray-200'>Explore from Apartments, land, builder floors,</span>
              <span className='text-gray-200'> villas and more</span>
              <a href='./buy'><button className='bg-blue-500 text-white px-4 py-2 rounded-xl mt-4 w-40'>Buy Now</button></a>
            </div>
        </div>
      </div>

      <div className='flex text-black justify-between py-6 mt-20 px-40 bg-gray-300 text-lg'>
        <div className='flex items-center gap-1'>Copyright <AiOutlineCopyrightCircle /> 2022 All rights reserved.</div>
        <span>Built by  <a href="https://twitter.com/dineshaitham1" target="_blank" className='underline underline-offset-2'>Dinesh Aitham</a></span>
      </div>

    </div>
  )
}
